version: '3'
services:
  minha-aplicacao:
    build: .
    ports:
      - "32781:8080"
    networks:
      api-email:
        ipv4_address: 172.22.0.100 
networks:
  api-email:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
